version: 2
jobs:
  build:
    working_directory: ~/website
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: v1-website-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Save bundle cache
        key: v1-website-{{ checksum "Gemfile.lock" }}
        paths:
          - ./vendor/bundle

      - run: bundle exec rake test
